name: super-rofl-test
version: 0.1.0
tee: tdx
kind: container
resources:
  memory: 512
  cpus: 1
  storage:
    kind: disk-persistent
    size: 512
artifacts:
  firmware: https://github.com/oasisprotocol/oasis-boot/releases/download/v0.6.2/ovmf.tdx.fd#db47100a7d6a0c1f6983be224137c3f8d7cb09b63bb1c7a5ee7829d8e994a42f
  kernel: https://github.com/oasisprotocol/oasis-boot/releases/download/v0.6.2/stage1.bin#e5d4d654ca1fa2c388bf64b23fc6e67815893fc7cb8b7cfee253d87963f54973
  stage2: https://github.com/oasisprotocol/oasis-boot/releases/download/v0.6.2/stage2-podman.tar.bz2#b2ea2a0ca769b6b2d64e3f0c577ee9c08f0bb81a6e33ed5b15b2a7e50ef9a09f
  container:
    runtime: https://github.com/oasisprotocol/oasis-sdk/releases/download/rofl-containers%2Fv0.8.2/rofl-containers#e9589c9cb68aee146a61ceefcce749ef5a391258dd26dc3037027733d883839f
    compose: compose.yaml
deployments:
  default:
    app_id: rofl1qzxqyhft2fe0cj3mwa5dzpkfarrwky225ynazpgp
    network: testnet
    paratime: sapphire
    admin: test:grace
    trust_root:
      height: 29272056
      hash: 765b5b454811b1305a3d34066adddb0dd88eb6e963b1cc64fc190d46c861ee83
    policy:
      quotes:
        pcs:
          tcb_validity_period: 30
          min_tcb_evaluation_data_number: 18
          tdx: {}
      enclaves:
        - id: TmyVCMskfadzei6BSBwi2m0B5Iq4/29WXm9+BZ6Ruv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
        - id: JUtR2jVqdQhKNkshMzzhRb/GWRS4/MQ6VvKDWHxoE7EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
      endorsements:
        - any: {}
      fees: endorsing_node
      max_expiration: 3
